const https = require('https');
const PDFDocument = require('pdfkit-table');
const { Parser } = require('json2csv');

exports.generateCSV = (data, fields) => {
    try {
        const json2csvParser = new Parser({ fields });
        const csv = json2csvParser.parse(data);
        return csv;
    } catch (err) {
        console.error('Error in generateCSV utility:', err);
        throw err;
    }
};

exports.generatePDF = async (res, title, data, headers, adminName) => {
    return new Promise(async (resolve, reject) => {
        try {
            const doc = new PDFDocument({ margin: 30, size: 'A4', bufferPages: true });

            // Pipe output to response
            doc.pipe(res);

            // Header
            doc.fontSize(20).text('Food Delivery App', { align: 'center' });
            doc.moveDown(0.5);
            doc.fontSize(16).text(title, { align: 'center' });
            doc.moveDown(0.5);
            doc.fontSize(10).text(`Generated By: ${adminName || 'Admin'}`, { align: 'right' });
            doc.text(`Generated On: ${new Date().toLocaleString()}`, { align: 'right' });
            doc.moveDown(1);

            // Table setup
            const table = {
                title: "",
                headers: headers.map(h => ({ label: h.label, property: h.id, width: h.width || 60, align: h.align || "left" })), // Added width
                datas: data.map(item => {
                    const row = {};
                    headers.forEach(h => {
                        let val = item[h.id];
                        if (val instanceof Date) {
                            val = val.toLocaleDateString();
                        } else if (typeof val === 'number') {
                            val = val.toFixed(2); // format money or numbers if needed
                        }
                        row[h.id] = val !== null && val !== undefined ? String(val) : '-';
                    });
                    return row;
                })
            };

            await doc.table(table, {
                prepareHeader: () => doc.font("Helvetica-Bold").fontSize(8),
                prepareRow: (row, indexColumn, indexRow, rectRow, rectCell) => {
                    doc.font("Helvetica").fontSize(8);
                },
                padding: 2, // Added padding for better spacing
            });

            // Render Chart if Profit/Loss Report
            if (title.includes('PROFIT_LOSS') && data && data.length > 0) {
                try {
                    const totalProfit = data[0].totalProfit || 0;
                    const totalLoss = data[0].totalLoss || 0;

                    if (totalProfit > 0 || totalLoss > 0) {
                        // Quickchart URL constructor
                        const chartUrl = `https://quickchart.io/chart?c={type:'pie',data:{labels:['Total Profit','Total Loss'],datasets:[{data:[${totalProfit},${totalLoss}],backgroundColor:['%2310b981','%23ef4444']}]}}`;

                        // Fetch the image buffer
                        const imageBuffer = await new Promise((resFetch, rejFetch) => {
                            https.get(chartUrl, (response) => {
                                const chunks = [];
                                response.on('data', (chunk) => chunks.push(chunk));
                                response.on('end', () => resFetch(Buffer.concat(chunks)));
                                response.on('error', rejFetch);
                            }).on('error', rejFetch);
                        });

                        doc.moveDown(2);
                        doc.fontSize(14).text('Profit vs Loss Visualization', { align: 'center' });
                        doc.moveDown();
                        doc.image(imageBuffer, {
                            fit: [300, 300],
                            align: 'center',
                            valign: 'center'
                        });
                    }
                } catch (chartErr) {
                    console.error('Error drawing pie chart in PDF:', chartErr);
                }
            }

            // Footer (Initial page, pdfkit-table doesn't always play well with pageAdded if async)
            doc.fontSize(8).text('Confidential - Admin Use Only', 30, doc.page.height - 30, { align: 'center' });

            doc.end();
            resolve();
        } catch (err) {
            console.error('Error generating PDF utility:', err);
            reject(err);
        }
    });
};
